title: SalesTim Open Source Code of Conduct
description: This code of conduct outlines expectations for participation in SalesTim-managed open source communities, as well as steps for reporting unacceptable behavior.
theme: jekyll-theme-minimal
logo: https://store.salestim.com/color.png
show_downloads: false
